
language: node_js
node_js:
  - "node"
  - "lts/*"

before_install:
  - npm i -g npm@6.2.0

before_script:
  - npm run clean
  - npm run setup

script:
  - npm build
  - npm run test

after_success:
  - npm run report-coverage